# Generated by Django 4.2.7 on 2026-05-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
